services:
  kes-site-node:
    container_name: kes-site-node
    build:
      context: .
      dockerfile: ./Dockerfile
    image: kes-site-node
    restart: always   
    ports:
      - "${PORT:-3001}:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 