version: "3.8"

services:
  kes-site-node:
    container_name: kes-site-node
    build:
      context: .
      dockerfile: ./Dockerfile
    image: kes-site-node
    restart: always
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=3001
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - FILE_STORAGE_MOUNT=/app/public/uploads
      - DATABASE_URL=mysql://root:rootpassword@db:3306/kes-site
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: kes-site-mysql
    ports:
      - "3307:3306" # Изменен внешний порт на 3307
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kes-site
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
