version: '3.8'

services:
  kes-site-node:
    container_name: kes-site-node
    build:
      context: .
      dockerfile: ./Dockerfile
    image: kes-site-node
    restart: always   
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - FILE_STORAGE_MOUNT=/app/public/uploads

networks:
  app-network:
    driver: bridge 