services:
  site-node:
    container_name: site-node
    build:
      context: .
      dockerfile: ./Dockerfile
    image: site-node
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 